<?php
/**
 * Enqueue Vite assets (dev server or production manifest).
 *
 * @package Minimal_Maison
 */

defined( 'ABSPATH' ) || exit;

/**
 * Vite dev server URL (host machine while WordPress runs in Docker).
 *
 * @return string
 */
function minimal_maison_vite_server(): string {
	return apply_filters( 'minimal_maison_vite_server', 'http://localhost:5173' );
}

/**
 * Path to Vite manifest (Vite 5+: dist/.vite/manifest.json).
 *
 * @return string|null
 */
function minimal_maison_vite_manifest_path(): ?string {
	$candidates = array(
		MM_THEME_DIR . '/dist/.vite/manifest.json',
		MM_THEME_DIR . '/dist/manifest.json',
	);

	foreach ( $candidates as $path ) {
		if ( is_readable( $path ) ) {
			return $path;
		}
	}

	return null;
}

/**
 * Whether to load assets from the Vite dev server.
 *
 * Local + no production manifest = development mode.
 *
 * @return bool
 */
function minimal_maison_is_vite_dev(): bool {
	if ( function_exists( 'wp_get_environment_type' ) && 'local' !== wp_get_environment_type() ) {
		return false;
	}

	return null === minimal_maison_vite_manifest_path();
}

/**
 * Read Vite manifest generated by `npm run build`.
 *
 * @return array<string, mixed>|null
 */
function minimal_maison_vite_manifest(): ?array {
	$path = minimal_maison_vite_manifest_path();

	if ( null === $path ) {
		return null;
	}

	$data = json_decode( (string) file_get_contents( $path ), true );

	return is_array( $data ) ? $data : null;
}

/**
 * Enqueue theme scripts and styles.
 */
function minimal_maison_enqueue_assets(): void {
	$entry_key = 'resources/js/app.js';

	if ( minimal_maison_is_vite_dev() ) {
		$server = untrailingslashit( minimal_maison_vite_server() );

		wp_enqueue_script(
			'minimal-maison-vite-client',
			$server . '/@vite/client',
			array(),
			null,
			true
		);

		wp_enqueue_script(
			'minimal-maison-app',
			$server . '/resources/js/app.js',
			array( 'minimal-maison-vite-client' ),
			null,
			true
		);

		return;
	}

	$manifest = minimal_maison_vite_manifest();

	if ( ! $manifest || empty( $manifest[ $entry_key ] ) ) {
		return;
	}

	$entry = $manifest[ $entry_key ];

	if ( ! empty( $entry['file'] ) ) {
		$js_path = MM_THEME_DIR . '/dist/' . ltrim( $entry['file'], '/' );
		$version = is_readable( $js_path ) ? (string) filemtime( $js_path ) : MM_THEME_VERSION;

		wp_enqueue_script(
			'minimal-maison-app',
			MM_THEME_URI . '/dist/' . ltrim( $entry['file'], '/' ),
			array(),
			$version,
			true
		);
	}

	if ( ! empty( $entry['css'] ) && is_array( $entry['css'] ) ) {
		foreach ( $entry['css'] as $index => $css_file ) {
			$css_path = MM_THEME_DIR . '/dist/' . ltrim( $css_file, '/' );
			$version  = is_readable( $css_path ) ? (string) filemtime( $css_path ) : MM_THEME_VERSION;

			wp_enqueue_style(
				'minimal-maison-app-' . $index,
				MM_THEME_URI . '/dist/' . ltrim( $css_file, '/' ),
				array(),
				$version
			);
		}
	}
}
add_action( 'wp_enqueue_scripts', 'minimal_maison_enqueue_assets' );

/**
 * Load script tags as ES modules (Vite).
 *
 * @param string $tag    Script tag.
 * @param string $handle Handle.
 * @param string $src    Source.
 * @return string
 */
function minimal_maison_script_module_tag( string $tag, string $handle, string $src ): string {
	$handles = array( 'minimal-maison-vite-client', 'minimal-maison-app' );

	if ( in_array( $handle, $handles, true ) ) {
		return sprintf(
			'<script type="module" src="%s" id="%s-js"></script>' . "\n",
			esc_url( $src ),
			esc_attr( $handle )
		);
	}

	return $tag;
}
add_filter( 'script_loader_tag', 'minimal_maison_script_module_tag', 10, 3 );
